# This file configures the analyzer for Dart/Flutter.
# https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print

